server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: studentModule
          uri: http://localhost:8080
          predicates:
            - Path=/api/{id}/**
          filters:
            - CustomFilter